# Generated by Django 3.2.15 on 2022-09-23 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porteiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': 'Porteiros'},
        ),
    ]
